name: oral_fit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.6.1

  flutter_native_splash: ^2.1.1
  font_awesome_flutter: ^9.2.0
  get_storage: ^2.0.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^4.0.2
  qrscan: ^0.3.2
  permission_handler: ^8.3.0
  flutter_switch: ^0.3.2
  image_picker: ^0.8.4+4

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

fonts:
    - family: Noto_Serif_KR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_L.png
  android: true
  ios: false
  web: false

  android_12:
    image: assets/images/splash_L.png