name: oral_fit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  
  flutter: 
    sdk: flutter
  splash_screen_view: ^3.0.0
  font_awesome_flutter: ^9.2.0
  get_storage: ^2.0.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0

  flutter_localizations:
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

fonts:
    - family: Noto_Serif_KR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700


